import { platformStore } from './platform-store.js';

const state={stats:{},brands:[],feed:[],query:''};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>Number(v||0).toLocaleString('tr-TR');
const pct=v=>Math.max(0,Math.min(100,Math.round(Number(v||0))));
const pathNow=()=>location.pathname.replace(/\/+$/,'')||'/';

async function rpc(name,args={}){if(!platformStore?.supabase)throw new Error('Veri servisi hazır değil');const r=await platformStore.supabase.rpc(name,args);if(r.error)throw r.error;return r.data}
function reliability(b){const n=Number(b.total_complaints||b.complaint_count||0);return n>=500?'Çok yüksek':n>=100?'Yüksek':n>=25?'Orta':'Gelişiyor'}
function logo(b){const n=b?.name||'G',u=b?.logo_url||b?.brand_logo_url;return u?'<span class="ghLogoImg"><img src="'+esc(u)+'" alt="'+esc(n)+'"></span>':'<span class="ghLogoImg fb">'+esc(n[0]||'G')+'</span>'}
function filtered(){const q=state.query.trim().toLocaleLowerCase('tr-TR');return (q?state.brands.filter(b=>[b.name,b.category,b.slug].some(x=>String(x||'').toLocaleLowerCase('tr-TR').includes(q))):state.brands).slice(0,6)}
function brandCard(b){const s=pct(b.trust_score);return '<a class="ghCard" href="/marka/'+encodeURIComponent(b.slug||'')+'"><div class="ghCardTop">'+logo(b)+'<div><b>'+esc(b.name||'Marka')+'</b><small>'+esc(b.category||'Genel')+'</small></div><strong>'+s+'</strong></div><div class="ghBar"><i style="width:'+s+'%"></i></div><div class="ghMeta"><span><b>'+pct(b.resolution_rate)+'%</b><small>çözüm</small></span><span><b>'+(Number(b.avg_response_hours||0)?Number(b.avg_response_hours).toFixed(1)+' sa':'—')+'</b><small>yanıt</small></span><span><b>'+esc(b.trend||'+0%')+'</b><small>30 gün</small></span></div><p>Veri güvenilirliği: <b>'+reliability(b)+'</b></p></a>'}
function complaint(r){const id=r.public_id||r.case_id||'',d=r.public_summary||r.description||r.details||'',st=String(r.status||'').toLowerCase(),label=['resolved','closed','solved'].includes(st)?'Çözüldü':['brand_replied','answered','responded'].includes(st)?'Marka Yanıtladı':'Açık';return '<a class="ghCase" href="/sikayet/'+encodeURIComponent(id)+'"><div><b>'+esc(r.brand_name||'Marka')+'</b><span>'+esc(r.category||'Genel')+'</span><em class="'+(label==='Çözüldü'?'ok':'')+'">'+label+'</em></div><h3>'+esc(r.title||'Kullanıcı deneyimi')+'</h3><p>'+esc(d).slice(0,180)+(String(d).length>180?'…':'')+'</p></a>'}
function metric(v,l){return '<div class="ghMetric"><b>'+v+'</b><span>'+l+'</span></div>'}

function render(){
 if(pathNow()!=='/')return;
 install();
 document.body.classList.add('ghHomeActive');
 let root=document.getElementById('gh-home-v2');if(!root){root=document.createElement('div');root.id='gh-home-v2';document.body.appendChild(root)}
 const s=state.stats||{},hero=state.brands[0]||{},cards=filtered(),feed=state.feed.slice(0,5);
 root.innerHTML='<header class="ghHead"><div class="ghNav"><a class="ghBrand" href="/"><span>✓</span><b>Güveniyorum<em>.com</em></b></a><nav><a href="/markalar">Markalar</a><a href="/sikayetler">Şikâyetler</a><a href="/markalar">Güvenilir mi?</a><a href="/marka-yonetimi">Kurumsal</a></nav><div><a class="ghost" href="/giris-yap">Giriş Yap</a><a class="dark" href="/sikayet-olustur">Şikâyet Yaz</a></div></div></header>'+
 '<main><section class="ghHero"><div class="ghWrap heroGrid"><div><span class="kicker">● TÜRKİYE’NİN GÜVEN KATMANI</span><h1>Bir markaya güvenmeden önce, <em>veriye bak.</em></h1><p>Şikâyetleri, çözüm oranlarını, yanıt hızını ve gerçek kullanıcı deneyimlerini tek bir güven görünümünde karşılaştır.</p><form class="ghSearch" data-search><input value="'+esc(state.query)+'" placeholder="Marka, site veya şirket ara…"><button>Ara</button></form></div><aside class="trustBox"><small>CANLI GÜVEN GÖRÜNÜMÜ</small><h3>'+esc(hero.name||'Örnek marka')+'</h3><div class="score"><b>'+pct(hero.trust_score||84)+'</b><span>Güven Skoru<small>Veri güvenilirliği: '+reliability(hero)+'</small></span></div><div class="boxMeta"><span><b>'+pct(hero.resolution_rate)+'%</b>çözüm</span><span><b>'+(Number(hero.avg_response_hours||0)?Number(hero.avg_response_hours).toFixed(1)+' sa':'—')+'</b>ilk yanıt</span><span><b>'+fmt(s.published_evidence)+'</b>kanıt</span></div></aside></div></section>'+
 '<section class="ghStats"><div class="ghWrap statsGrid">'+metric(fmt(s.published_complaints),'Kamusal deneyim')+metric(fmt(s.resolved_complaints),'Çözülen şikâyet')+metric(fmt(s.open_complaints),'Aktif süreç')+metric(fmt(s.published_evidence),'Görünür kanıt')+'</div></section>'+
 '<section class="ghSec"><div class="ghWrap"><div class="secHead"><div><span>MARKA KARNELERİ</span><h2>Güven bir sayı değil, <em>davranış biçimi.</em></h2><p>Skorun yanında çözüm oranını, yanıt hızını, trendi ve veri güvenilirliğini birlikte gösteriyoruz.</p></div><a href="/markalar">Tüm markaları gör →</a></div><div class="cardGrid">'+(cards.length?cards.map(brandCard).join(''):'<div class="empty">Aramana uyan marka bulunamadı.</div>')+'</div></div></section>'+
 '<section class="ghDark"><div class="ghWrap"><div class="darkHead"><div><span>TRUST INTELLIGENCE</span><h2>Veriyi sadece göstermiyoruz.<br><em>Anlamlandırıyoruz.</em></h2></div><p>Çözüm performansı, tekrarlayan sorunlar ve yanıt hızı; markanın sorun yaşadığında nasıl davrandığını gösterir.</p></div><div class="intel"><article><i>↗</i><b>Çözüm Performansı</b><p>Kullanıcı sonucuyla birlikte gerçek kapanış oranı.</p></article><article><i>◎</i><b>Tekrarlayan Sorunlar</b><p>Kategori bazında tekrar eden problem örüntüleri.</p></article><article><i>◷</i><b>Yanıt Hızı</b><p>İlk tepki ve çözüm süresini ayrı sinyaller olarak izle.</p></article></div></div></section>'+
 '<section class="ghSec white"><div class="ghWrap feedGrid"><div><div class="secHead mini"><div><span>SON DENEYİMLER</span><h2>Şikâyet akışı</h2></div><a href="/sikayetler">Tümünü gör →</a></div><div class="cases">'+(feed.length?feed.map(complaint).join(''):'<div class="empty">Henüz kamusal şikâyet verisi yok.</div>')+'</div></div><aside class="decision"><span>GÜVENİLİR Mİ?</span><h3>Karar vermeden önce markayı ara.</h3><p>Güven skoru, çözüm davranışı ve son şikâyet trendlerini tek ekranda incele.</p><form data-search><input placeholder="Marka adını yaz…"><button>→</button></form><div class="method"><b>Metodoloji şeffaflığı</b><p>Skor; çözüm, yanıt, tekrar ve kullanıcı doğrulaması gibi sinyallerden oluşur.</p><a href="/guven-merkezi">Nasıl hesaplanır? →</a></div></aside></div></section>'+
 '<section class="business"><div class="ghWrap bizGrid"><div><span>GÜVENİYORUM BUSINESS</span><h2>Müşterileriniz zaten konuşuyor.<br><em>Siz de masada olun.</em></h2><p>Şikâyete cevap vermek ve çözüm üretmek ücretsiz. Gelişmiş analiz, ekip yönetimi ve CRM katmanı Business tarafında.</p><a href="/marka-yonetimi">Kurumsal hesabı keşfet</a></div><div class="mock"><b>84</b><span>Güven Skoru</span><i>+3.2</i><hr><p>Çözüm oranı <strong>76%</strong></p><p>İlk yanıt <strong>1.8 sa</strong></p></div></div></section>'+
 '<section class="ghSec"><div class="ghWrap"><div class="secHead"><div><span>NASIL ÇALIŞIR?</span><h2>Şikâyetten güven verisine.</h2></div></div><div class="steps"><article><b>1</b><span>Deneyimini paylaş</span></article><article><b>2</b><span>Marka yanıtlasın</span></article><article><b>3</b><span>Çözümü doğrula</span></article><article><b>4</b><span>Güven verisine dönüşsün</span></article></div></div></section></main>'+
 '<footer><div class="ghWrap"><div class="footTop"><a class="ghBrand" href="/"><span>✓</span><b>Güveniyorum<em>.com</em></b></a><p>Şikâyet → Çözüm → Doğrulama → Güven Skoru → Daha bilinçli karar.</p></div></div></footer>';
 bind();
}

function bind(){
 document.querySelectorAll('[data-search]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const input=f.querySelector('input');state.query=input?.value||'';const first=filtered()[0];location.href=first?.slug?'/marka/'+encodeURIComponent(first.slug):'/markalar'}));
 const hero=document.querySelector('.ghSearch input');if(hero)hero.addEventListener('input',e=>{state.query=e.target.value;const grid=document.querySelector('.cardGrid');if(grid){const cards=filtered();grid.innerHTML=cards.length?cards.map(brandCard).join(''):'<div class="empty">Aramana uyan marka bulunamadı.</div>'}});
}

function install(){
 if(document.getElementById('gh-home-v2-style'))return;
 const s=document.createElement('style');s.id='gh-home-v2-style';s.textContent=`
 :root{--g:#0b8f5c;--gd:#07583d;--ink:#0b1713;--muted:#6d7974;--line:#dfe7e3;--bg:#f6f8f7;--dark:#07130f}
 body.ghHomeActive{margin:0!important;background:var(--bg)!important;color:var(--ink);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:-.018em}body.ghHomeActive #root{display:none!important}
 #gh-home-v2 *{box-sizing:border-box}#gh-home-v2 a{text-decoration:none;color:inherit}#gh-home-v2 button,#gh-home-v2 input{font:inherit}.ghWrap{width:min(1280px,calc(100% - 64px));margin:auto}
 .ghHead{position:sticky;top:0;z-index:80;background:rgba(255,255,255,.9);backdrop-filter:blur(18px);border-bottom:1px solid rgba(11,23,19,.08)}.ghNav{height:76px;width:min(1320px,calc(100% - 48px));margin:auto;display:flex;align-items:center;gap:32px}.ghBrand{display:flex;align-items:center;gap:9px;font-weight:800}.ghBrand>span{width:36px;height:36px;display:grid;place-items:center;border-radius:12px;background:var(--g);color:#fff}.ghBrand b{font-size:18px}.ghBrand em{font-style:normal;color:var(--g)}.ghNav nav{display:flex;gap:24px;margin-left:auto}.ghNav nav a{font-size:13px;font-weight:650;color:#34413b}.ghNav>div{display:flex;gap:9px}.ghNav>div a{padding:10px 14px;border-radius:12px;font-size:12px;font-weight:750}.ghNav .ghost{border:1px solid var(--line);background:#fff}.ghNav .dark{background:var(--dark);color:#fff}
 .ghHero{padding:82px 0 70px;background:radial-gradient(circle at 84% 10%,rgba(11,143,92,.12),transparent 36%),linear-gradient(180deg,#fff,#f6f8f7);border-bottom:1px solid var(--line)}.heroGrid{display:grid;grid-template-columns:1.1fr .9fr;gap:70px;align-items:center}.kicker,.secHead>div>span,.darkHead span,.business>div>div>span,.decision>span{color:var(--gd);font-size:10px;font-weight:850;letter-spacing:.12em}.ghHero h1{margin:18px 0 22px;font-size:clamp(52px,6.8vw,88px);line-height:.96;letter-spacing:-.065em}.ghHero h1 em,.ghSec h2 em,.ghDark h2 em,.business h2 em{font-style:normal;color:var(--g)}.ghHero p{max-width:690px;color:var(--muted);font-size:18px;line-height:1.65}
 .ghSearch{margin-top:28px;display:grid;grid-template-columns:1fr auto;gap:10px;padding:8px;background:#fff;border:1px solid #d5dfda;border-radius:17px;box-shadow:0 16px 50px rgba(15,40,29,.08)}.ghSearch input{height:48px;border:0;outline:0;padding:0 12px;font-size:15px}.ghSearch button,.decision button{border:0;background:var(--gd);color:#fff;border-radius:12px;font-weight:800}.ghSearch button{padding:0 20px}.trustBox{padding:23px;background:#fff;border:1px solid rgba(11,23,19,.1);border-radius:26px;box-shadow:0 28px 80px rgba(10,48,32,.12)}.trustBox>small{font-size:8px;color:#85918c;letter-spacing:.12em}.trustBox h3{margin:5px 0 0}.score{display:flex;align-items:center;gap:17px;padding:22px 0}.score>b{font-size:60px;color:var(--gd);letter-spacing:-.07em}.score span,.score small{display:block}.score small{margin-top:4px;color:var(--muted);font-size:10px}.boxMeta{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.boxMeta span{padding:11px;background:#f6f8f7;border-radius:13px;font-size:8px;color:#7e8a85}.boxMeta b{display:block;margin-bottom:4px;color:var(--ink);font-size:14px}
 .ghStats{background:#fff;border-bottom:1px solid var(--line)}.statsGrid{display:grid;grid-template-columns:repeat(4,1fr)}.ghMetric{padding:27px 28px;border-right:1px solid var(--line)}.ghMetric:first-child{border-left:1px solid var(--line)}.ghMetric b,.ghMetric span{display:block}.ghMetric b{font-size:30px}.ghMetric span{margin-top:5px;font-size:11px;font-weight:750}
 .ghSec{padding:82px 0;background:var(--bg)}.ghSec.white{background:#fff}.secHead{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:28px}.secHead h2,.ghDark h2,.business h2{margin:10px 0;font-size:clamp(34px,4.2vw,58px);line-height:1;letter-spacing:-.055em}.secHead p{max-width:700px;color:var(--muted);line-height:1.6}.secHead>a{white-space:nowrap;color:var(--gd);font-size:12px;font-weight:800}.secHead.mini h2{font-size:38px}
 .cardGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.ghCard{padding:18px;background:#fff;border:1px solid var(--line);border-radius:19px;transition:.2s}.ghCard:hover{transform:translateY(-3px);box-shadow:0 22px 55px rgba(18,55,39,.08)}.ghCardTop{display:flex;align-items:center;gap:10px}.ghLogoImg{width:43px;height:43px;display:grid;place-items:center;border:1px solid #e3e9e6;border-radius:12px;overflow:hidden}.ghLogoImg img{width:100%;height:100%;object-fit:contain}.ghLogoImg.fb{background:var(--dark);color:#fff;font-weight:900}.ghCardTop>div b,.ghCardTop>div small{display:block}.ghCardTop>div small{margin-top:3px;color:#8b9691;font-size:9px}.ghCardTop>strong{margin-left:auto;font-size:27px;color:var(--gd)}.ghBar{height:5px;margin:15px 0;background:#edf2ef;border-radius:99px;overflow:hidden}.ghBar i{display:block;height:100%;background:linear-gradient(90deg,var(--g),#43cb91)}.ghMeta{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.ghMeta span{padding:8px;border-radius:10px;background:#f7f9f8;text-align:center}.ghMeta b,.ghMeta small{display:block}.ghMeta b{font-size:11px}.ghMeta small{font-size:7px;color:#8a9591}.ghCard>p{padding-top:10px;border-top:1px solid #edf1ef;color:#75827d;font-size:8px}
 .ghDark{padding:86px 0;background:var(--dark);color:#fff}.darkHead{display:grid;grid-template-columns:1.1fr .9fr;gap:70px;align-items:end}.darkHead span{color:#7ce1af}.darkHead>p{color:#98aca3;line-height:1.7}.intel{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:40px}.intel article{padding:23px;border:1px solid rgba(255,255,255,.09);border-radius:19px;background:rgba(255,255,255,.035)}.intel i{width:40px;height:40px;display:grid;place-items:center;border-radius:12px;background:#123b2c;color:#69dfa8;font-style:normal}.intel b{display:block;margin-top:30px}.intel p{margin:7px 0 0;color:#95aaa1;font-size:11px;line-height:1.6}
 .feedGrid{display:grid;grid-template-columns:1.35fr .65fr;gap:21px}.cases{display:grid;gap:9px}.ghCase{padding:16px 17px;border:1px solid var(--line);border-radius:16px;background:#fff}.ghCase>div{display:flex;align-items:center;gap:8px}.ghCase>div>span{font-size:8px;color:#8b9691}.ghCase em{margin-left:auto;padding:5px 8px;border-radius:999px;background:#fff1e5;color:#b45c14;font-size:8px;font-style:normal}.ghCase em.ok{background:#e7f7ef;color:#08714a}.ghCase h3{margin:10px 0 5px;font-size:16px}.ghCase p{margin:0;color:#6f7c77;font-size:10px;line-height:1.6}.decision{align-self:start;position:sticky;top:96px;padding:23px;border:1px solid #dce7e1;border-radius:21px;background:#f4f8f6}.decision h3{font-size:26px;line-height:1.05}.decision p{color:#718079;font-size:11px;line-height:1.6}.decision form{display:grid;grid-template-columns:1fr 40px;gap:6px;margin-top:15px;padding:6px;background:#fff;border:1px solid #d8e4de;border-radius:12px}.decision input{border:0;outline:0;padding:0 8px}.method{margin-top:17px;padding-top:16px;border-top:1px solid #d7e2dc}.method a{color:var(--gd);font-size:9px;font-weight:800}
 .business{padding:86px 0;background:#0b2b20;color:#fff}.bizGrid{display:grid;grid-template-columns:1.05fr .95fr;gap:75px;align-items:center}.business>div>div>span{color:#7ce1af}.business p{max-width:630px;color:#a6bbb2;line-height:1.7}.business a{display:inline-block;margin-top:18px;padding:11px 15px;background:#fff;color:#0b2b20!important;border-radius:11px;font-size:11px;font-weight:800}.mock{padding:22px;border-radius:21px;background:#f5f8f6;color:var(--ink)}.mock>b{font-size:52px;color:var(--gd)}.mock>span{margin-left:9px;font-weight:700}.mock>i{float:right;color:var(--g)}.mock p{color:#718079}.mock strong{float:right;color:var(--ink)}
 .steps{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.steps article{padding:20px;border:1px solid var(--line);border-radius:17px;background:#fff}.steps article b{width:32px;height:32px;display:grid;place-items:center;border-radius:9px;background:#e8f7f0;color:var(--gd)}.steps article span{display:block;margin-top:30px;font-size:13px;font-weight:750}
 footer{padding:54px 0;background:#06100d;color:#fff}.footTop{display:flex;justify-content:space-between;gap:30px}.footTop p{color:#92a79e}
 .empty{grid-column:1/-1;padding:25px;border:1px dashed #cfdad4;border-radius:16px;color:#7a8781;text-align:center}
 @media(max-width:1000px){.ghNav nav{display:none}.heroGrid,.darkHead,.bizGrid,.feedGrid{grid-template-columns:1fr}.cardGrid{grid-template-columns:repeat(2,1fr)}.intel{grid-template-columns:1fr}.statsGrid{grid-template-columns:repeat(2,1fr)}.steps{grid-template-columns:repeat(2,1fr)}.decision{position:static}}
 @media(max-width:680px){.ghWrap{width:min(100% - 28px,1280px)}.ghNav{width:min(100% - 24px,1320px);height:68px}.ghNav .ghost{display:none}.ghHero{padding:52px 0}.heroGrid{gap:32px}.ghHero h1{font-size:48px}.ghHero p{font-size:15px}.ghSearch{grid-template-columns:1fr}.ghSearch button{display:none}.boxMeta{grid-template-columns:1fr}.statsGrid{grid-template-columns:1fr 1fr}.ghMetric{padding:19px 15px}.cardGrid,.steps{grid-template-columns:1fr}.ghSec,.ghDark,.business{padding:62px 0}.secHead{align-items:flex-start;flex-direction:column}.footTop{flex-direction:column}}
 `;
 document.head.appendChild(s)
}

async function boot(){
 if(pathNow()!=='/')return;
 render();
 const [a,b,c]=await Promise.allSettled([rpc('get_public_reputation_stats'),rpc('get_public_brand_directory',{p_search:null,p_limit:24}),rpc('get_public_reputation_feed',{p_search:null,p_status:'all',p_category:null,p_brand_slug:null,p_limit:12,p_offset:0})]);
 if(a.status==='fulfilled'&&a.value)state.stats=a.value;if(b.status==='fulfilled'&&Array.isArray(b.value))state.brands=b.value;if(c.status==='fulfilled'&&Array.isArray(c.value))state.feed=c.value;render()
}
boot();
