const menuItems = [
  ['/', 'Ana Sayfa', ''], ['/site-ligi', 'Site Ligi', 'HOT'], ['/kullanici-yarismasi', 'Kullanıcı Yarışması', 'NEW'], ['/guven-merkezi', 'Güven Merkezi', ''], ['/sorumlu-oyun', 'Sorumlu Oyun', 'ÖNEMLİ'], ['/oyuncu-psikolojisi', 'Oyuncu Psikolojisi', 'YARDIM'], ['/wellness-merkezi', 'Wellness Merkezi', 'YENİ'], ['/topluluk-merkezi', 'Topluluk Merkezi', '1.2K'], ['/ai-danisman', 'AI Danışman', 'AI'], ['/sertifikasyon', 'Sertifikasyon', ''], ['/kampanyalar', 'Kampanyalar', '12'], ['/sohbet', 'Sohbet', '247'], ['/sikayetler', 'Şikayetler', '89'], ['/marketing-marketplace', 'Marketing Marketplace', ''], ['/sertifika-basvurusu', 'Sertifika Başvurusu', ''], ['/marka-yonetimi', 'Marka Yönetimi', ''], ['/yardim', 'Yardım', ''],
];

const sites = [
  { name: 'GüvenBet', domain: 'guvenbet.com', year: 2020, label: 'Temel Güven', score: 88, rating: '4.3 — 567 değerlendirme', users: '76K', complaints: 18, response: '5s', min: '50₺', tags: ['Güvenli Altyapı', 'Hızlı KYC', 'Bonus Çeşitliliği', 'Mobil Uyum'], pros: ['Güvenli ödeme sistemi', 'Hızlı hesap doğrulama', 'Çeşitli bonus seçenekleri'], risks: [] },
  { name: 'BetSafe', domain: 'betsafe.example', year: 2018, label: 'Premium Güven', score: 98, rating: '4.8 — 2.1K değerlendirme', users: '125K', complaints: 7, response: '2s', min: '100₺', tags: ['Lisanslı', 'Hızlı Destek', 'VIP Program', 'Şeffaf Oran'], pros: ['Çok hızlı ödeme', 'Güçlü kullanıcı memnuniyeti', '7/24 canlı destek'], risks: [] },
  { name: 'RiskPlay', domain: 'riskplay.example', year: 2024, label: 'İncelemede', score: 62, rating: '3.1 — 91 değerlendirme', users: '12K', complaints: 44, response: '18s', min: '250₺', tags: ['Yeni Site', 'Casino', 'Yüksek Bonus'], pros: ['Geniş oyun kataloğu'], risks: ['Yavaş müşteri hizmetleri', 'KYC zorunlu değil', 'Yüksek çevrim şartları', 'Mobil uygulama yok', 'Ödeme süreçleri gecikiyor'] },
];
const leagues = [
  ['BetSafe', 'Bahis & Casino', ['Efsanevi', 'Güven Lideri', 'Kullanıcı Favorisi', 'Hızlı Destek'], 98, '98%', '4.8/5', '125K', '+12 sıra'],
  ['GüvenBet', 'Bahis Siteleri', ['Epik', 'Temel Güven'], 88, '88%', '4.3/5', '76K', '+4 sıra'],
  ['NovaCasino', 'Casino Siteleri', ['Nadir', 'Mobil Uyum'], 81, '84%', '4.1/5', '41K', '-2 sıra'],
];
const contributors = [['BahisGuru','Bahis Analizi','Level 42','18.400 XP',['Uzman','Güvenilir'],128,74,912,21],['CasinoExpert','Casino Specialist','Level 39','16.900 XP',['Casino Specialist','Popüler'],116,61,803,18],['GüvenliOyuncu','Güvenlik Uzmanı','Level 35','14.200 XP',['Yardımsever','Şikayet Çözücü'],92,88,701,36],['BonusAvcısı','Bonus Analizi','Level 31','12.700 XP',['Moderatör','Uzman'],84,47,655,14]];
const complaintStatuses = ['Yeni','Moderasyon İncelemesinde','Marka Yanıtı Bekleniyor','Çözüm Sürecinde','Çözüldü','Doğrulanamadı','Reddedildi','Riskli'];

function normalizePath(pathname) { return pathname !== '/' && pathname.endsWith('/') ? pathname.slice(0, -1) : pathname; }
function go(path) { history.pushState({}, '', path); render(); }
function link(path, label, cls='') { return `<a href="${path}" class="${cls}" data-route>${label}</a>`; }
function action(label, type='modal') { return `<button class="action" data-action="${type}" data-label="${label}">${label}</button>`; }
function pills(items) { return `<div class="pills">${items.map((x) => `<span>${x}</span>`).join('')}</div>`; }
function tabs(items) { return `<div class="tabs">${items.map((x, i) => `<button class="${i === 0 ? 'active' : ''}">${x}</button>`).join('')}</div>`; }
function statCards(items) { return `<div class="stats">${items.map(([n,l]) => `<article class="stat"><strong>${n}</strong><span>${l}</span></article>`).join('')}</div>`; }
function section(title, text, body='') { return `<section class="panel"><div class="section-head"><div><h2>${title}</h2><p>${text}</p></div></div>${body}</section>`; }

function siteCards() { return `<div class="filters">${['Tüm Siteler','Güvenilir Siteler','Sertifikalı Siteler','Kara Liste','Yeni Siteler','Bahis Siteleri','Casino Siteleri','Bahis & Casino'].map((f,i)=>`<button class="${i===0?'active':''}">${f}</button>`).join('')}<select><option>Güven Skoruna Göre</option></select></div><div class="site-grid">${sites.map(site => `<article class="site-card ${site.risks.length ? 'risky' : ''}"><div class="card-top"><div><h3>${site.name}</h3><small>${site.domain} · ${site.year} yılından beri</small></div><span class="score">${site.score}%</span></div><b class="trust-label">${site.label}</b><div class="metrics"><span>★ ${site.rating}</span><span>${site.users} Kullanıcı</span><span>${site.complaints} Şikayet</span><span>${site.response} Yanıt Süresi</span><span>${site.min} Min. Yatırım</span></div>${pills(site.tags)}<h4>Avantajlar</h4><ul>${site.pros.map(p=>`<li>${p}</li>`).join('')}</ul>${site.risks.length ? `<div class="risk"><b>DİKKAT!</b>${site.risks.map(r=>`<span>${r}</span>`).join('')}</div>` : ''}<div class="card-actions">${action('Detayları Gör','detail')}${action('Siteye Git','detail')}</div></article>`).join('')}</div>`; }
function home() { return `<section class="hero"><div><span class="eyebrow">Türkiye’nin #1 Bahis Güvenlik Platformu</span><h1>Güvenli Bahis <span>Kontrol Sende</span></h1><p>Yapay zeka destekli güvenlik analizi ile bahis sitelerini değerlendir, toplulukla deneyim paylaş ve güvenli bahis deneyimi yaşa.</p><div class="hero-actions">${link('/guvenilir-siteler','Güvenli Siteleri Keşfet','primary')}${link('/sikayetler','Şikayet Oluştur','secondary')}</div></div><div class="hero-card"><b>%98</b><span>Güven Skoru</span><small>Kontrol Sende</small></div></section>${statCards([['150+','Güvenilir Site'],['50K+','Aktif Kullanıcı'],['12K+','Çözülen Şikayet'],['%98','Güven Skoru']])}${section('En Güvenilir Bahis Siteleri','Türkiye’deki tüm bahis sitelerini güvenlik, kullanıcı memnuniyeti ve güvenilirlik açısından değerlendiriyoruz.', siteCards())}${leaguePage(true)}${contributorsPage(true)}${trustCenter(true)}${section('Siteler Arası Rekabet','Güven skorunu yükselt, toplulukta görünür ol ve hizmet kalitenle öne çık.', statCards([['3','Aktif Yarışma'],['₺2,500','Günlük Ödül'],['98.5%','Lig Güveni']]))}`; }
function leaguePage(compact=false) { const body = `${tabs(['Liderlik Tablosu','Aktif Yarışmalar','Performans Metrikleri','Kara Liste'])}${pills(['Tüm Seviyeler','Efsanevi','Epik','Nadir','Yaygın'])}<div class="league-grid">${leagues.map(l=>`<article class="card"><h3>${l[0]}</h3><p>${l[1]}</p>${pills(l[2])}<div class="metric-list"><b>Lig Puanı: ${l[3]}</b><span>Güven Skoru: ${l[4]}</span><span>Kullanıcı Puanı: ${l[5]}</span><span>Kullanıcı Sayısı: ${l[6]}</span><em>${l[7]}</em></div></article>`).join('')}</div>`; return compact ? section('Türkiye Bahis Siteleri Ligi','Güvenlik, kullanıcı memnuniyeti ve hizmet kalitesine göre siteler arası rekabet', body) : pageTitle('Türkiye Bahis Siteleri Ligi','Güvenlik, kullanıcı memnuniyeti ve hizmet kalitesine göre siteler arası rekabet') + body; }
function contributorsPage(compact=false) { const body = `<div class="user-grid">${contributors.map(u=>`<article class="card"><h3>${u[0]}</h3><p>${u[1]} · ${u[2]} · ${u[3]}</p>${pills(u[4])}<div class="metrics"><span>${u[5]} İnceleme</span><span>${u[6]} Çözüm</span><span>${u[7]} Faydalı oy</span><span>${u[8]} Şikayet</span></div></article>`).join('')}</div>`; return compact ? section('En Aktif Katkı Sağlayanlar','Topluluk için en çok katkı sağlayan, güvenilir ve deneyimli üyelerimiz', body) : pageTitle('En Aktif Katkı Sağlayanlar','Topluluk için en çok katkı sağlayan, güvenilir ve deneyimli üyelerimiz') + body; }
function trustCenter(compact=false) { const body = `${tabs(['Genel Bakış','Doğrulama Seviyeleri','Güvenlik Özellikleri','Şeffaflık Raporu'])}${statCards([['98.5%','Platform Güvenlik Skoru'],['96.8%','Topluluk Güven Oranı'],['94.2%','Şeffaflık Puanı'],['97.1%','Yanıt Hızı Skoru']])}<div class="status"><b>Platform durumu</b><span>99.9% Uptime</span><span>2.3s Ortalama Yanıt</span><span>0 Güvenlik İhlali</span><strong>Tüm Sistemler Çalışıyor</strong></div>`; return compact ? section('Güvenlik ve Şeffaflık','Platform güvenliğimiz, kullanıcı doğrulama sistemimiz ve şeffaflık politikalarımız', body) : pageTitle('Güvenlik ve Şeffaflık','Platform güvenliğimiz, kullanıcı doğrulama sistemimiz ve şeffaflık politikalarımız') + body; }
function pageTitle(title, text) { return `<section class="page-title"><h1>${title}</h1><p>${text}</p></section>`; }
function responsible() { return pageTitle('Güvenli ve Sorumlu Oyun','Oyun deneyiminizi kontrol altında tutun, sağlıklı sınırlar belirleyin ve gerektiğinde yardım alın.') + tabs(['Genel Bakış','Kendini Değerlendir','Kontrol Araçları','Yardım Al']) + cardList(['Zaman Kontrolü','Bütçe Yönetimi','Duygusal Kontrol','Sosyal Destek']) + section('Uyarı İşaretleri','Riskli davranışları erken fark edin.', `<ul class="warning-list">${['Oyun oynamak için borç almak','Kayıpları geri kazanmak için daha fazla oynamak','Oyun hakkında yalan söylemek','Oyun süresini kontrol edememek','Oyun yüzünden sosyal ilişkileri ihmal etmek','Oyun oynamadığında huzursuzluk hissetmek'].map(x=>`<li>${x}</li>`).join('')}</ul>`); }
function psychology() { return pageTitle('Psikolojik Farkındalık Testi','Oyun alışkanlıklarınızın psikolojik boyutlarını değerlendirin ve sağlıklı oyun davranışları geliştirin.') + tabs(['Psikolojik Tuzaklar','Psikolojik Test','Duygusal Durumlar','Kontrol Araçları','Eğitim Kaynakları']) + statCards([['15','soru'],['5-8 dk','süre'],['%100','anonim'],['Anında','sonuç']]) + `<section class="panel test"><h2>Soru 1/15</h2><p>Günde ortalama ne kadar süre bahis ile ilgili aktivitelerle geçirirsiniz?</p>${['30 dakikadan az','30 dakika - 2 saat arası','2-5 saat arası','5 saatten fazla'].map(x=>`<label class="radio"><input name="q" type="radio">${x}</label>`).join('')}<div class="card-actions">${action('Teste Başla','test')}${action('Sonuçları Yazdır','detail')}${action('Uzman Desteği Al','detail')}</div><div class="result"><b>Sonuç ekranı</b><span>Güçlü Yönleriniz</span><span>Dikkat Edilmesi Gerekenler</span><span>Kişiselleştirilmiş Öneriler</span></div></section>`; }
function wellness() { return pageTitle('Ruh Sağlığı ve Wellness Merkezi','Sağlıklı oyun alışkanlıkları geliştirin, uzman desteği alın ve toplulukla birlikte iyileşin.') + statCards([['1,247','Aktif Program Katılımcısı'],['89','Tamamlanan Program'],['4.8/5','Ortalama Memnuniyet'],['24','Uzman Danışman']]) + tabs(['Wellness Programları','Destek Hizmetleri','Kaynaklar','Topluluk']) + cardList(['Mindful Gaming Program','Healthy Limits Workshop','7/24 Kriz Hattı','Online Terapi Seansları','Grup Terapisi','Aile Danışmanlığı']) + `<section class="emergency"><h2>Acil Durum Desteği</h2><p>Kendinize zarar verme düşünceleriniz varsa hemen yardım alın. 7/24 kriz hattımız sizin için burada.</p><strong>0850 123 45 67</strong>${action('Canlı Destek','chat')}</section>`; }
function community() { return pageTitle('Birlikte İyileşiyoruz','Güvenli bir ortamda deneyimlerinizi paylaşın, destek alın ve başkalarına ilham verin.') + statCards([['50,247','Toplam Üye'],['1,247','Aktif Tartışma'],['8,934','Paylaşılan Deneyim'],['15,678','Verilen Destek']]) + tabs(['Forum','Etkinlikler','Başarı Hikayeleri','Mentorluk']) + cardList(['Destek ve Yardım','İyileşme Hikayeleri','İpuçları ve Stratejiler','Genel Sohbet','30 gün temiz kaldım!','Mindfulness Atölyesi']); }
function aiAdvisor() { return pageTitle('Yapay Zeka Destekli Rehberlik','Kişiselleştirilmiş AI danışmanlarımızdan güvenlik, psikoloji ve strateji konularında destek alın.') + `<section class="ai-layout"><div>${['Dr. Psikoloji — Oyuncu Psikolojisi','Güvenlik Uzmanı — Site Güvenliği','Analiz Uzmanı — Bahis Analizi','Kişisel Danışman — Genel Rehberlik'].map(x=>`<button>${x}<small>%98 güven</small></button>`).join('')}</div><div class="chat"><p class="ai">Merhaba, güvenli kararlar için buradayım. <b>%99 güven</b></p><p class="me">Bu site güvenli mi?</p><input placeholder="Mesajınızı yazın..."><button class="action">Gönder</button></div><aside>${pills(['Bu site güvenli mi?','Sağlıklı bahis limitleri nedir?','Kayıp kovalama nasıl önlenir?','En güvenilir ödeme yöntemleri?','Bonus şartları nasıl değerlendirilir?','Duygusal kontrol teknikleri neler?'])}</aside></section>`; }
function campaigns() { return simplePage('Heyecan Verici Kampanyalar','Katılın, yarışın ve harika ödüller kazanın! Her hafta yeni fırsatlar sizi bekliyor.',['Aktif Kampanyalar','Geçmiş Kampanyalar','Kurallar','Liderlik'],['Yılbaşı Mega Kampanya','₺50,000 nakit havuzu','iPhone 15 Pro','MacBook Air','100 adet AirPods','2,847 / 5,000'], 'Kampanyaya Katıl'); }
function marketplace() { return simplePage('Pazarlama Çözümleri Merkezi','Siteniz için ihtiyacınız olan tüm pazarlama hizmetlerini tek yerden alın.',['Hizmetler','Sağlayıcılar','Siparişlerim','Satıcı Ol'],['Meta Reklam Yönetimi — ₺2,500/ay','Push Notification Sistemi — ₺1,200/ay','E-mail Marketing Paketi — ₺800/ay','Telegram Bot & Kanal Yönetimi','Influencer Marketing','SEO & İçerik Optimizasyonu'], 'Sipariş Ver'); }
function certificateApply() { return simplePage('Güvenilirliğinizi Belgeleyin','Guveniyorum.com güven sertifikası ile kullanıcılarınıza güvenilirliğinizi kanıtlayın.',['Sertifika Seviyeleri','Başvuru Yap','Sertifikalı Siteler','Süreç'],['Temel Güven Sertifikası — ₺2,500/yıl','Gelişmiş Güven Sertifikası — ₺7,500/yıl','Premium Güven Sertifikası — ₺15,000/yıl','SSL sertifikası','Lisans belgesi','AI destekli güvenlik'], 'Başvuru Yap'); }
function brandManage() { return pageTitle('Marka İtibarınızı Yönetin','Markanızın güvenilirliğini artırın, müşteri geri bildirimlerini yönetin ve itibarınızı koruyun.') + tabs(['Dashboard','İncelemeler','Şikayetler','Analitik','Ayarlar']) + `<section class="panel form-panel"><label>Marka Adı<input value="GüvenBet"></label><label>Marka Açıklaması<textarea>Güvenilir bahis deneyimi.</textarea></label><label>İletişim E-postası<input value="iletisim@guvenbet.com"></label><label>Telefon<input value="0850 000 00 00"></label><div class="card-actions">${action('İptal','modal')}${action('Değişiklikleri Kaydet','save')}</div></section>`; }
function complaints() { return pageTitle('Şikayetler','Şikayet oluştur, akışı takip et, marka yanıtlarını ve çözüm durumunu gör.') + `<section class="panel"><div class="section-head"><h2>Şikayet Akışı</h2>${action('Şikayet Oluştur','complaint')}</div><div class="flow">${complaintStatuses.map(s=>`<span>${s}</span>`).join('')}</div><div id="complaintForm" class="complaint-form hidden">${['Site / Marka adı','Domain','Şikayet konusu','Şikayet başlığı','Olay tarihi','İşlem tutarı','Ödeme yöntemi','Açıklama','Kanıt yükle','Talep edilen çözüm','Gizlilik tercihi','Yayın onayı'].map(x=>`<label>${x}<input placeholder="${x}"></label>`).join('')}<button class="action" data-action="submitComplaint">Gönder</button></div><div id="complaintResult" class="result hidden"><b>Şikayet dosyan oluşturuldu.</b><span>Dosya No: GVN-2026-0001</span><span>Durum: Moderasyon incelemesinde</span></div><article class="card"><h3>Şikayet Detayı</h3><p>Marka Yanıtı · Çözüm Durumu · Topluluk Yorumu · Kanıt Seviyesi · Platform Değerlendirmesi</p>${action('Yanıtla','detail')}</article></section>`; }
function simplePage(title,text,tabItems,cards,button) { return pageTitle(title,text) + tabs(tabItems) + `<div class="cards">${cards.map(c=>`<article class="card"><h3>${c}</h3><p>Doğrulanmış sağlayıcı, yüksek puan ve hızlı teslim süresi.</p>${action(button,'detail')}</article>`).join('')}</div>`; }
function cardList(items) { return `<div class="cards">${items.map(i=>`<article class="card"><h3>${i}</h3><p>Detay paneli, yönlendirme ve demo işlem akışı hazır.</p>${action(i.includes('Program')?'Programa Katıl':i.includes('Terapi')?'Randevu Al':'Kategoriye Git','detail')}</article>`).join('')}</div>`; }
function auth(title) { return pageTitle(title, title === 'Üye Ol' ? 'Hesabını oluştur, markaları takip et ve güven skorlarına göre karar ver.' : 'Değerlendirdiğin markalara ve şikayet geçmişine eriş.') + `<section class="panel form-panel"><label>E-posta<input type="email"></label><label>Şifre<input type="password"></label>${action(title,'save')}</section>`; }

const pages = {'/':home,'/guvenilir-siteler':()=>pageTitle('En Güvenilir Bahis Siteleri','Arama, kategori filtreleri ve güven skoruna göre sıralama.')+`<input class="wide-search" placeholder="Site ara...">`+siteCards(),'/site-ligi':leaguePage,'/kullanici-yarismasi':contributorsPage,'/guven-merkezi':trustCenter,'/sorumlu-oyun':responsible,'/oyuncu-psikolojisi':psychology,'/wellness-merkezi':wellness,'/topluluk-merkezi':community,'/ai-danisman':aiAdvisor,'/sertifikasyon':certificateApply,'/kampanyalar':campaigns,'/sohbet':()=>simplePage('Sohbet','Toplulukla güvenli şekilde bağlantı kur.',['Genel','Destek','Markalar'],['Canlı oda','Marka temsilcisi','Destek kanalı'],'Kategoriye Git'),'/sikayetler':complaints,'/marketing-marketplace':marketplace,'/sertifika-basvurusu':certificateApply,'/marka-yonetimi':brandManage,'/yardim':()=>simplePage('Yardım','Platform rehberi ve destek merkezi.',['SSS','Destek','İletişim'],['Başlangıç rehberi','Güven skoru nasıl çalışır?','Destek talebi'],'Detayları Gör'),'/giris-yap':()=>auth('Giriş Yap'),'/giris':()=>auth('Giriş Yap'),'/uye-ol':()=>auth('Üye Ol')};
function sidebar(current) { return `<aside class="sidebar"><div class="logo"><b>Güveniyorum</b><span>Kontrol Sende</span></div><nav>${menuItems.map(([p,l,b])=>link(p,`${l}${b?`<em>${b}</em>`:''}`,normalizePath(current)===p?'active':'' )).join('')}</nav><div class="side-stats"><span>Online Kullanıcı: <b>1,247</b></span><span>Aktif Yarışma: <b>3</b></span><span>Günlük Ödül: <b>₺2,500</b></span><span>Güven Skoru: <b>%98.5</b></span></div></aside>`; }
function topbar() { return `<header class="topbar"><button class="menu-toggle" data-action="menu">☰</button><input placeholder="Site ara, şikayet bul, kullanıcı ara..."><div class="top-icons"><button>🔔</button><button>✉</button><button>⚙</button>${link('/giris-yap','Giriş Yap','login')}${link('/uye-ol','Üye Ol','join')}</div></header>`; }
function modal(label) { return `<div class="modal"><div><button class="close" data-action="close">×</button><h2>${label}</h2><p>${label} için demo detay paneli açıldı. Bu aksiyon boş değil; ürün akışı burada modal, form veya state olarak simüle edilir.</p>${action('Tamam','close')}</div></div>`; }
function render() { const currentPath = normalizePath(window.location.pathname); const page = pages[currentPath] || pages['/']; document.querySelector('#root').innerHTML = `${sidebar(currentPath)}<main class="app">${topbar()}<div class="content">${page()}</div></main><button class="live" data-action="chat">Canlı Destek</button><div id="modalRoot"></div>`; bind(); }
function bind() { document.querySelectorAll('[data-route]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();go(a.getAttribute('href'));})); document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>handle(b.dataset.action,b.dataset.label||b.textContent))); }
function handle(type,label) { const m=document.querySelector('#modalRoot'); if(type==='close') return m.innerHTML=''; if(type==='menu') return document.body.classList.toggle('sidebar-open'); if(type==='complaint') return document.querySelector('#complaintForm')?.classList.toggle('hidden'); if(type==='submitComplaint') { document.querySelector('#complaintResult')?.classList.remove('hidden'); return; } if(type==='test') return m.innerHTML=modal('Psikolojik test sonucu: Güçlü Yönleriniz, Dikkat Edilmesi Gerekenler ve Kişiselleştirilmiş Öneriler'); m.innerHTML=modal(label); bind(); }
window.addEventListener('popstate', render); render();
