import { inject } from '@vercel/analytics';

inject();

const menu=[
['/','Ana Sayfa',''],['/marka-ligi','Marka Ligi','HOT'],['/kullanici-yarismasi','Kullanıcı Yarışması','NEW'],['/guven-merkezi','Güven Merkezi',''],['/sorumlu-kullanim','Sorumlu Kullanım','ÖNEMLİ'],['/kullanici-psikolojisi','Kullanıcı Psikolojisi','YARDIM'],['/wellness-merkezi','Wellness Merkezi','YENİ'],['/topluluk-merkezi','Topluluk Merkezi','1.2K'],['/ai-danisman','AI Danışman','AI'],['/sertifikasyon','Sertifikasyon',''],['/farkindalik-programlari','Farkındalık Programları','12'],['/sohbet','Sohbet','247'],['/sikayetler','Şikayetler','89'],['/seffaflik-marketplace','Şeffaflık Marketplace',''],['/sertifika-basvurusu','Sertifika Başvurusu',''],['/marka-yonetimi','Marka Yönetimi',''],['/yardim','Yardım',''],['/giris-yap','Giriş Yap',''],['/uye-ol','Üye Ol','']];
const aliases={'/marka-karsilastirma':'/marka-ligi','/misafir-kullanici':'/','/giris':'/giris-yap'};
const brands=[
{name:'SafeMark',domain:'safemark.example',year:'2018',tag:'Efsanevi',score:98,rating:'4.8',users:'125K',complaints:12,response:'2 saat',min:'₺50 işlem',labels:['Güven Lideri','Kullanıcı Favorisi','Hızlı Destek'],pros:['Lisans şeffaflığı yüksek','Hızlı doğrulama','Güçlü destek performansı'],risks:[],trend:'+12'},
{name:'GüvenMark',domain:'guvenmark.example',year:'2020',tag:'Temel Güven',score:88,rating:'4.3',users:'76K',complaints:18,response:'5 saat',min:'₺50 işlem',labels:['Güvenli Altyapı','Hızlı KYC','Mobil Uyum'],pros:['Güvenli ödeme sistemi','Hızlı hesap doğrulama','Şeffaf iletişim'],risks:['Yanıt süresi dönemsel yavaşlıyor'],trend:'+4'},
{name:'RiskMark',domain:'riskmark.example',year:'2024',tag:'Yakın Takip',score:52,rating:'2.9',users:'14K',complaints:89,response:'36 saat',min:'₺100 işlem',labels:['Yeni Marka','Yakın İzleme'],pros:['Hızlı arayüz','Aktif bildirim akışı'],risks:['KYC süreci zayıf','Yüksek şart yoğunluğu','Ödeme süreçleri gecikiyor'],trend:'-9'}
];
const users=[['GüvenGuru','Marka Güvenliği',42,'18,240 XP','Uzman,Güvenilir,Moderatör',312,94],['AnalizExpert','Risk Analizi',38,'15,870 XP','Analiz Uzmanı,Yardımsever',274,81],['ŞikayetÇözücü','Dosya Takibi',31,'12,100 XP','Çözüm Uzmanı,Popüler',198,73],['ŞeffaflıkAvcısı','Şart Analizi',29,'10,780 XP','Topluluk,Doğrulayıcı',221,54]];
let modal='',created=false,mobile=false,notice='';
const q=s=>document.querySelector(s);
const norm=p=>{p=p!=='/'&&p.endsWith('/')?p.slice(0,-1):p;return aliases[p]||p};
const nav=p=>{history.pushState({},'',p);mobile=false;window.scrollTo(0,0);render()};
const a=(p,t,c='')=>`<a href="${p}" class="${c}" data-route>${t}</a>`;
const metric=(v,t)=>`<article class="metric"><b>${v}</b><span>${t}</span></article>`;
const title=(h,p)=>`<div class="section-title"><div><h2>${h}</h2><p>${p}</p></div></div>`;
const tags=x=>`<div class="tags">${x.map(i=>`<span>${i}</span>`).join('')}</div>`;
const btn=(t,act,c='secondary')=>`<button class="${c}-btn" data-action="${act||t}">${t}</button>`;
const openModal=(h,b)=>{modal=`<div class="modal"><article><button class="close" data-close>×</button><h3>${h}</h3>${b}</article></div>`;render()};
const demo=(text)=>{notice=text;openModal('İşlem Merkezi',`<p>${text}</p><div class="modal-grid"><span>Durum: Hazır</span><span>Kayıt: Demo state</span><span>Kontrol: Aktif</span></div>${btn('Tamam','modal kapat','primary')}`)};
function brandCard(b){return `<article class="brand-card ${b.risks.length?'danger':''}"><div class="brand-head"><div><small>${b.tag}</small><h3>${b.name}</h3><p>${b.domain} · ${b.year} yılından beri</p></div><div class="score"><b>${b.score}%</b><span>Güven</span></div></div><div class="info-grid"><span>⭐ ${b.rating}</span><span>👥 ${b.users}</span><span>⚠️ ${b.complaints} şikayet</span><span>⏱ ${b.response}</span><span>💳 ${b.min}</span><span>📈 ${b.trend}</span></div>${tags(b.labels)}<div class="pros"><b>Avantajlar</b>${b.pros.map(p=>`<p>✓ ${p}</p>`).join('')}</div>${b.risks.length?`<div class="warn"><b>DİKKAT!</b>${b.risks.map(r=>`<p>${r}</p>`).join('')}</div>`:''}<div class="actions">${btn('Detayları Gör',b.name+' detay paneli açıldı')}${btn('Risk Raporunu Aç',b.name+' risk raporu açıldı','primary')}</div></article>`}
function brandSection(){return `<section class="panel">${title('En Güvenilir Markalar','Markaları güvenlik, kullanıcı memnuniyeti ve şikayet çözüm performansı açısından değerlendiriyoruz.')}<div class="toolbar"><input data-search placeholder="Marka adı, domain veya şikayet ara..."/><select><option>Güven Skoruna Göre</option><option>Şikayet yoğunluğuna göre</option><option>Yanıt hızına göre</option></select></div><div class="pills">${['Tüm Markalar','Güvenilir Markalar','Sertifikalı Markalar','Kara Liste','Yeni Markalar','Yüksek Risk'].map(x=>btn(x,x+' filtresi açıldı','pill')).join('')}</div><div class="brand-list">${brands.map(brandCard).join('')}</div></section>`}
function league(){return `<section class="panel">${title('Türkiye Marka Güvenliği Ligi','Güvenlik, kullanıcı memnuniyeti ve hizmet kalitesine göre markalar arası rekabet.')}<div class="tabs">${['Liderlik Tablosu','Aktif Yarışmalar','Performans Metrikleri','Kara Liste'].map((x,i)=>`<button class="${i?'':'active'}" data-action="${x} açıldı">${x}</button>`).join('')}</div><div class="league">${brands.map((b,i)=>`<article><b>#${i+1}</b><div><h3>${b.name}</h3><p>${b.tag} · ${b.labels.slice(0,2).join(' / ')}</p></div><strong>${b.score}</strong><span>${b.trend} sıra</span></article>`).join('')}</div></section>`}
function contributors(){return `<section class="panel">${title('En Aktif Katkı Sağlayanlar','Topluluk için en çok katkı sağlayan, güvenilir ve deneyimli üyelerimiz.')}<div class="cards4">${users.map(u=>`<article class="glass"><div class="avatar">${u[0][0]}</div><h3>${u[0]}</h3><p>${u[1]}</p><div class="bar"><span style="width:${Math.min(u[2]*2,100)}%"></span></div><b>Level ${u[2]} · ${u[3]}</b>${tags(u[4].split(','))}<div class="mini"><span>${u[5]} İnceleme</span><span>${u[6]} Çözüm</span></div>${btn('Profili İncele',u[0]+' profil paneli açıldı')}</article>`).join('')}</div></section>`}
function trust(){return `<section class="panel">${title('Güvenlik ve Şeffaflık','Platform güvenliğimiz, kullanıcı doğrulama sistemimiz ve şeffaflık politikalarımız.')}<div class="metrics">${metric('98.5%','Platform Güvenlik Skoru')}${metric('96.8%','Topluluk Güven Oranı')}${metric('94.2%','Şeffaflık Puanı')}${metric('97.1%','Yanıt Hızı Skoru')}</div><div class="status"><span>99.9% Uptime</span><span>2.3s Ortalama Yanıt</span><span>0 Güvenlik İhlali</span><span>Tüm Sistemler Çalışıyor</span></div></section>`}
function home(){return `<section class="hero"><small>Türkiye’nin #1 Şikayet ve Marka Güvenliği Platformu</small><h1>Güvenli Karar<br><span>Kontrol Sende</span></h1><p>Yapay zekâ destekli risk analizi ile markaları değerlendir, toplulukla deneyim paylaş ve güvenli karar sürecini yönet.</p><div class="actions">${a('/marka-ligi','Marka Skorlarını İncele','primary-btn')}${a('/sikayetler','Şikayet Oluştur','secondary-btn')}</div></section><div class="metrics">${metric('150+','Güvenilir Marka')}${metric('50K+','Aktif Kullanıcı')}${metric('12K+','Çözülen Şikayet')}${metric('%98','Güven Skoru')}</div>${brandSection()}${league()}${contributors()}${trust()}`}
function generic(h,p,tabs,body){return `<section class="page-head"><h1>${h}</h1><p>${p}</p></section><section class="panel"><div class="tabs">${tabs.map((x,i)=>`<button class="${i?'':'active'}" data-action="${x} açıldı">${x}</button>`).join('')}</div>${body}</section>`}
function responsible(){let w=['Borç alarak işlem yapmak','Kayıpları geri kazanmak için daha fazla risk almak','Yakın çevreye gerçek durumu saklamak','Süre kontrolünü kaybetmek','Sosyal ilişkileri ihmal etmek','Ara verince huzursuzluk hissetmek'];return generic('Güvenli ve Sorumlu Kullanım','Deneyiminizi kontrol altında tutun, sağlıklı sınırlar belirleyin ve gerektiğinde yardım alın.',['Genel Bakış','Kendini Değerlendir','Kontrol Araçları','Yardım Al'],`<div class="cards4">${['Zaman Kontrolü','Bütçe Yönetimi','Duygusal Kontrol','Sosyal Destek'].map(x=>`<article class="glass"><h3>${x}</h3><p>Limit, takip ve erken uyarı araçları.</p>${btn('Aracı Aç',x+' aracı açıldı')}</article>`).join('')}</div><div class="warn wide"><b>Uyarı İşaretleri</b>${w.map(x=>`<p>${x}</p>`).join('')}</div>`) }
function psychology(){return generic('Psikolojik Farkındalık Testi','Kullanım alışkanlıklarınızın psikolojik boyutlarını değerlendirin ve sağlıklı davranışlar geliştirin.',['Psikolojik Tuzaklar','Psikolojik Test','Duygusal Durumlar','Kontrol Araçları','Eğitim Kaynakları'],`<div class="metrics">${metric('15','Soru')}${metric('5-8 dk','Süre')}${metric('%100','Anonim')}${metric('Anında','Sonuç')}</div><article class="test"><span>Soru 1/15</span><h3>Günde ortalama ne kadar süre platform ve risk değerlendirme aktiviteleriyle geçirirsiniz?</h3>${['30 dakikadan az','30 dakika - 2 saat','2-5 saat','5 saatten fazla'].map(x=>`<label><input type="radio" name="t"/> ${x}</label>`).join('')}<div class="actions">${btn('Teste Başla','Psikolojik test başlatıldı','primary')}${btn('Uzman Desteği Al','Uzman destek paneli açıldı')}</div></article>`) }
function wellness(){return generic('Ruh Sağlığı ve Wellness Merkezi','Sağlıklı alışkanlıklar geliştirin, uzman desteği alın ve toplulukla birlikte iyileşin.',['Wellness Programları','Destek Hizmetleri','Kaynaklar','Topluluk'],`<div class="metrics">${metric('1,247','Aktif Katılımcı')}${metric('89','Tamamlanan Program')}${metric('4.8/5','Memnuniyet')}${metric('24','Uzman Danışman')}</div><div class="cards4">${['Mindful Program','Healthy Limits Workshop','7/24 Kriz Hattı','Online Terapi Seansları'].map(x=>`<article class="glass"><h3>${x}</h3><p>Güvenli destek ve yönlendirme.</p>${btn('Programa Katıl',x+' kaydı açıldı','primary')}</article>`).join('')}</div><div class="emergency"><h3>Acil Durum Desteği</h3><p>Kendinize zarar verme düşünceleriniz varsa hemen yardım alın.</p><b>0850 123 45 67</b>${btn('Canlı Destek','Canlı destek başlatıldı')}</div>`) }
function community(){return generic('Birlikte İyileşiyoruz','Güvenli bir ortamda deneyimlerinizi paylaşın, destek alın ve başkalarına ilham verin.',['Forum','Etkinlikler','Başarı Hikayeleri','Mentorluk'],`<div class="metrics">${metric('50,247','Toplam Üye')}${metric('1,247','Aktif Tartışma')}${metric('8,934','Deneyim')}${metric('15,678','Destek')}</div><div class="cards4">${['Destek ve Yardım','İyileşme Hikayeleri','İpuçları ve Stratejiler','Genel Sohbet'].map(x=>`<article class="glass"><h3>${x}</h3><p>Topluluk kategorisi.</p>${btn('Kategoriye Git',x+' kategorisi açıldı')}</article>`).join('')}</div>`) }
function ai(){return `<section class="page-head"><h1>Yapay Zeka Destekli Rehberlik</h1><p>Kişiselleştirilmiş AI danışmanlarımızdan güvenlik, psikoloji ve strateji konularında destek alın.</p></section><section class="ai"><aside>${['Dr. Psikoloji','Güvenlik Uzmanı','Analiz Uzmanı','Kişisel Danışman'].map((x,i)=>`<button class="${i?'':'active'}" data-action="${x} seçildi">${x}<span>%${95+i} güven</span></button>`).join('')}</aside><article><div class="msg ai-msg">Merhaba. Marka güvenliği, psikolojik kontrol ve şikayet analizi için buradayım.</div><div class="msg user-msg">Bu marka güvenilir mi?</div><div class="msg ai-msg">Lisans, ödeme performansı, şikayet yoğunluğu ve topluluk değerlendirmesine göre risk sinyali üretirim.</div><form data-chat><input placeholder="Sorunuzu yazın..."/><button class="primary-btn">Gönder</button></form></article><aside>${['Bu marka güvenli mi?','Sağlıklı limitler nedir?','Kayıp kovalama nasıl önlenir?','Şartlar nasıl değerlendirilir?'].map(x=>btn(x,x+' yanıtlandı','ghost')).join('')}</aside></section>`}
function programs(){return generic('Farkındalık Programları','Katılım, öğrenme ve sağlıklı alışkanlık geliştirme programları.',['Aktif Programlar','Geçmiş Programlar','Kurallar','Liderlik'],`<article class="campaign"><h3>Kontrollü Kullanım Programı</h3><p>Haftalık takip, kişisel limit ve farkındalık görevleri.</p><div class="progress"><span style="width:57%"></span></div><p>2,847 / 5,000 katılımcı</p>${btn('Programa Katıl','Program katılım ekranı açıldı','primary')}</article>`) }
function marketplace(){return generic('Şeffaflık Marketplace','Markalar için şeffaflık, kullanıcı bilgilendirme ve destek hizmetlerini tek yerden yönetin.',['Hizmetler','Sağlayıcılar','Siparişlerim','Satıcı Ol'],`<div class="cards3">${['İtibar ve Şeffaflık Yönetimi','Kullanıcı Bilgilendirme Sistemi','Bildirim ve Bilgilendirme Paketi','Topluluk Destek Modülü','İçerik ve SEO Optimizasyonu','Analitik Raporlama'].map(x=>`<article class="glass"><small>Doğrulanmış</small><h3>${x}</h3><p>Teslim: 3-7 gün · Puan: 4.8</p>${btn('Sipariş Ver',x+' sipariş paneli açıldı','primary')}</article>`).join('')}</div>`) }
function certificate(){return generic('Güvenilirliğinizi Belgeleyin','Güveniyorum.com güven sertifikası ile kullanıcılara güvenilirliğinizi kanıtlayın.',['Sertifika Seviyeleri','Başvuru Yap','Sertifikalı Markalar','Süreç'],`<div class="cards3">${[['Temel Güven Sertifikası','₺2,500/yıl','SSL, lisans belgesi, müşteri hizmetleri'],['Gelişmiş Güven Sertifikası','₺7,500/yıl','KYC, anti-fraud, sorumlu kullanım politikası'],['Premium Güven Sertifikası','₺15,000/yıl','AI destekli güvenlik, sürekli monitoring']].map(x=>`<article class="glass"><h3>${x[0]}</h3><b>${x[1]}</b><p>${x[2]}</p>${btn('Başvuru Yap',x[0]+' başvurusu açıldı','primary')}</article>`).join('')}</div>`) }
function brandManage(){return `<section class="page-head"><h1>Marka İtibarınızı Yönetin</h1><p>Markanızın güvenilirliğini artırın, müşteri geri bildirimlerini yönetin ve itibarınızı koruyun.</p></section><section class="brand-manage"><article class="panel"><h3>Dashboard</h3>${metric('88%','Güven Skoru')}${metric('18','Aktif Şikayet')}${metric('5 saat','Yanıt Süresi')}</article><article class="panel"><h3>İncelemeler</h3><p>“Destek ekibi hızlı dönüş yaptı.”</p><p>“Şartlar daha açık yazılmalı.”</p>${btn('Yanıtla','Marka yanıt ekranı açıldı','primary')}</article><form class="form"><h3>Ayarlar</h3><input placeholder="Marka Adı"/><textarea placeholder="Marka Açıklaması"></textarea><input placeholder="İletişim E-postası"/><input placeholder="Telefon"/><button class="primary-btn">Değişiklikleri Kaydet</button></form></section>`}
function complaints(){return `<section class="page-head"><h1>Şikayetler</h1><p>Kullanıcı deneyimlerini kayıt altına al, kanıt seviyesini değerlendir ve çözüm sürecini takip et.</p></section><section class="complaints"><aside class="panel"><button class="primary-btn full" data-open-complaint>Şikayet Oluştur</button>${['Tümü','Yeni','Moderasyon İncelemesinde','Marka Yanıtı Bekleniyor','Çözüm Sürecinde','Çözüldü','Riskli'].map((x,i)=>`<button class="filter ${i?'':'active'}" data-action="${x} filtresi açıldı">${x}</button>`).join('')}</aside><article class="panel"><h3>Şikayet Akışı</h3>${created?`<div class="success"><b>GVN-2026-0001</b><span>Moderasyon incelemesinde</span><p>Marka: Örnek Marka · Konu: Para çekim gecikmesi</p></div>`:''}<div class="complaint"><b>GVN-2026-0002</b><span>Marka Yanıtı Bekleniyor</span><p>Hesap doğrulama sürecinde gecikme yaşandı.</p>${btn('Detayı Aç','GVN-2026-0002 detay paneli açıldı')}</div><div class="complaint"><b>GVN-2026-0003</b><span>Çözüldü</span><p>Yanlış bilgilendirme düzeltildi ve kullanıcıya dönüş yapıldı.</p>${btn('Detayı Aç','GVN-2026-0003 detay paneli açıldı')}</div></article><form class="form" data-complaint><h3>Şikayet Formu</h3><input required placeholder="Site / Marka adı"/><input placeholder="Domain"/><select><option>Para çekim sorunu</option><option>Ödeme gecikmesi</option><option>Hesap kapatma / kısıtlama</option><option>Bonus / şart sorunu</option><option>Destek sorunu</option></select><input placeholder="Şikayet başlığı"/><input type="date"/><input placeholder="İşlem tutarı"/><select><option>Ödeme yöntemi</option><option>Kart</option><option>Banka transferi</option><option>Kripto</option></select><textarea placeholder="Açıklama"></textarea><input type="file"/><textarea placeholder="Talep edilen çözüm"></textarea><label><input type="checkbox"/> Gizlilik tercihini onaylıyorum</label><label><input type="checkbox"/> Yayın / moderasyon onayı veriyorum</label><button class="primary-btn">Şikayeti Gönder</button></form></section>`}
function auth(kind){return `<section class="auth"><form class="form"><h1>${kind}</h1><p>Şikayetlerini takip etmek, marka skorlarını kaydetmek ve topluluk katkılarına erişmek için devam et.</p><input placeholder="E-posta"/><input placeholder="Şifre" type="password"/><button class="primary-btn">${kind}</button></form></section>`}
function help(){return generic('Yardım Merkezi','Platform kullanımı, şikayet süreci, sertifikasyon ve hesap işlemleri için hızlı destek.',['Sık Sorulanlar','Canlı Destek','Belgeler','İletişim'],`<div class="cards3">${['Şikayet nasıl oluşturulur?','Güven skoru nasıl hesaplanır?','Marka yanıtı nasıl takip edilir?'].map(x=>`<article class="glass"><h3>${x}</h3><p>Adım adım rehber ve destek akışı.</p>${btn('Aç',x+' yardım detayı açıldı')}</article>`).join('')}</div>`) }
const pages={'/':home,'/marka-ligi':()=>brandSection()+league(),'/kullanici-yarismasi':contributors,'/guven-merkezi':trust,'/sorumlu-kullanim':responsible,'/kullanici-psikolojisi':psychology,'/wellness-merkezi':wellness,'/topluluk-merkezi':community,'/ai-danisman':ai,'/sertifikasyon':certificate,'/farkindalik-programlari':programs,'/sohbet':()=>generic('Sohbet','Toplulukla güvenli ve kontrollü şekilde iletişim kur.',['Genel','Destek','Mentor'],`<div class="chatbox"><p>Canlı sohbet demo akışı</p><input placeholder="Mesaj yaz..."/>${btn('Gönder','Mesaj gönderildi','primary')}</div>`),'/sikayetler':complaints,'/seffaflik-marketplace':marketplace,'/sertifika-basvurusu':certificate,'/marka-yonetimi':brandManage,'/yardim':help,'/giris-yap':()=>auth('Giriş Yap'),'/uye-ol':()=>auth('Üye Ol')};
function sidebar(path){return `<aside class="sidebar ${mobile?'open':''}"><div class="logo"><b>G</b><div><strong>Güveniyorum</strong><span>Kontrol Sende</span></div></div><nav>${menu.map(m=>`<a href="${m[0]}" class="${norm(m[0])===path?'active':''}" data-route><span>${m[1]}</span>${m[2]?`<em>${m[2]}</em>`:''}</a>`).join('')}</nav><div class="side-stats"><p>Online Kullanıcı <b>1,247</b></p><p>Aktif Yarışma <b>3</b></p><p>Günlük Ödül <b>₺2,500</b></p><p>Güven Skoru <b>%98.5</b></p></div></aside>`}
function topbar(){return `<header class="topbar"><button data-menu>☰</button><input placeholder="Marka ara, şikayet bul, kullanıcı ara..."/><div><button data-action="Bildirimler açıldı">🔔</button><button data-action="Mesajlar açıldı">✉️</button>${a('/giris-yap','Giriş Yap','ghost-btn')}${a('/uye-ol','Üye Ol','primary-btn')}</div></header>`}
function modalBox(){return modal}
function render(){let p=norm(location.pathname),page=pages[p]||pages['/'];q('#root').innerHTML=`${sidebar(p)}<main>${topbar()}<div class="wrap">${notice?`<div class="notice">${notice}</div>`:''}${page()}</div></main><button class="live" data-action="Canlı destek başlatıldı">Canlı Destek</button>${modalBox()}`}
addEventListener('click',e=>{let r=e.target.closest('[data-route]');if(r){e.preventDefault();nav(r.getAttribute('href'))}if(e.target.closest('[data-menu]')){mobile=!mobile;render()}let ac=e.target.closest('[data-action]');if(ac){let t=ac.dataset.action;if(t==='modal kapat'){modal='';render()}else demo(t)}if(e.target.closest('[data-close]')){modal='';render()}if(e.target.closest('[data-open-complaint]')){q('[data-complaint]')?.scrollIntoView({behavior:'smooth',block:'start'})}});
addEventListener('submit',e=>{if(e.target.matches('[data-complaint]')){e.preventDefault();created=true;notice='Şikayet dosyan oluşturuldu. Dosya No: GVN-2026-0001 · Durum: Moderasyon incelemesinde';openModal('Şikayet dosyan oluşturuldu',`<p><b>Dosya No:</b> GVN-2026-0001</p><p><b>Durum:</b> Moderasyon incelemesinde</p><p>Dosyan şikayet akışına eklendi ve takip edilebilir.</p>${btn('Şikayet Akışını Gör','modal kapat','primary')}`)}if(e.target.matches('[data-chat]')){e.preventDefault();demo('AI danışman mesajı aldı ve analiz yanıtı hazırladı.')}});
addEventListener('popstate',render);render();
