import { inject } from '@vercel/analytics';

inject();

const menu=[
['/','Ana Sayfa',''],['/marka-ligi','Marka Ligi','HOT'],['/kullanici-yarismasi','Kullanıcı Yarışması','NEW'],['/guven-merkezi','Güven Merkezi',''],['/sorumlu-kullanim','Sorumlu Kullanım','ÖNEMLİ'],['/kullanici-psikolojisi','Kullanıcı Psikolojisi','YARDIM'],['/wellness-merkezi','Wellness Merkezi','YENİ'],['/topluluk-merkezi','Topluluk Merkezi','1.2K'],['/ai-danisman','AI Danışman','AI'],['/sertifikasyon','Sertifikasyon',''],['/farkindalik-programlari','Farkındalık Programları','12'],['/sohbet','Sohbet','247'],['/sikayetler','Şikayetler','89'],['/seffaflik-marketplace','Şeffaflık Marketplace',''],['/sertifika-basvurusu','Sertifika Başvurusu',''],['/marka-yonetimi','Marka Yönetimi',''],['/yardim','Yardım','']
];
const aliases={'/marka-karsilastirma':'/marka-ligi','/misafir-kullanici':'/','/giris':'/giris-yap'};
const brands=[
{name:'SafeMark',domain:'safemark.example',year:'2018',tag:'Efsanevi',score:98,rating:'4.8',users:'125K',complaints:12,response:'2 saat',min:'₺50 işlem',labels:['Güven Lideri','Kullanıcı Favorisi','Hızlı Destek'],pros:['Lisans şeffaflığı yüksek','Hızlı doğrulama','Güçlü destek performansı'],risks:[]},
{name:'GüvenMark',domain:'guvenmark.example',year:'2020',tag:'Temel Güven',score:88,rating:'4.3',users:'76K',complaints:18,response:'5 saat',min:'₺50 işlem',labels:['Güvenli Altyapı','Hızlı KYC','Mobil Uyum'],pros:['Güvenli ödeme sistemi','Hızlı hesap doğrulama','Şeffaf iletişim'],risks:['Yanıt süresi dönemsel yavaşlıyor']},
{name:'RiskMark',domain:'riskmark.example',year:'2024',tag:'Yakın Takip',score:52,rating:'2.9',users:'14K',complaints:89,response:'36 saat',min:'₺100 işlem',labels:['Yeni Marka','Yakın İzleme'],pros:['Hızlı arayüz','Aktif bildirim akışı'],risks:['KYC süreci zayıf','Yüksek şart yoğunluğu','Ödeme süreçleri gecikiyor']}
];
const users=[['GüvenGuru','Marka Güvenliği',42,'18,240 XP','Uzman,Güvenilir,Moderatör',312,94],['AnalizExpert','Risk Analizi',38,'15,870 XP','Analiz Uzmanı,Yardımsever',274,81],['ŞikayetÇözücü','Dosya Takibi',31,'12,100 XP','Çözüm Uzmanı,Popüler',198,73],['ŞeffaflıkAvcısı','Şart Analizi',29,'10,780 XP','Topluluk,Doğrulayıcı',221,54]];
let modal='',created=false,mobile=false;
const q=s=>document.querySelector(s);
const norm=p=>{p=p!=='/'&&p.endsWith('/')?p.slice(0,-1):p;return aliases[p]||p};
const nav=p=>{history.pushState({},'',p);mobile=false;render()};
const a=(p,t,c='')=>`<a href="${p}" class="${c}" data-route>${t}</a>`;
const metric=(v,t)=>`<article class="metric"><b>${v}</b><span>${t}</span></article>`;
const title=(h,p)=>`<div class="section-title"><h2>${h}</h2><p>${p}</p></div>`;
const tags=x=>`<div class="tags">${x.map(i=>`<span>${i}</span>`).join('')}</div>`;
const btn=(t,act,c='secondary')=>`<button class="${c}-btn" data-action="${act||t}">${t}</button>`;
function brandCard(b){return `<article class="brand-card ${b.risks.length?'danger':''}"><div class="brand-head"><div><small>${b.tag}</small><h3>${b.name}</h3><p>${b.domain} · ${b.year} yılından beri</p></div><div class="score"><b>${b.score}%</b><span>Güven</span></div></div><div class="info-grid"><span>⭐ ${b.rating}</span><span>👥 ${b.users}</span><span>⚠️ ${b.complaints} şikayet</span><span>⏱ ${b.response}</span><span>💳 ${b.min}</span><span>🏷 ${b.tag}</span></div>${tags(b.labels)}<div class="pros"><b>Avantajlar</b>${b.pros.map(p=>`<p>✓ ${p}</p>`).join('')}</div>${b.risks.length?`<div class="warn"><b>DİKKAT!</b>${b.risks.map(r=>`<p>${r}</p>`).join('')}</div>`:''}<div class="actions">${btn('Detayları Gör',b.name+' detay paneli açıldı')}${btn('Risk Raporunu Aç',b.name+' risk raporu açıldı','primary')}</div></article>`}
function brandSection(){return `<section class="panel">${title('En Güvenilir Markalar','Markaları güvenlik, kullanıcı memnuniyeti ve şikayet çözüm performansı açısından değerlendiriyoruz.')}<div class="toolbar"><input placeholder="Marka adı, domain veya şikayet ara..." /><select><option>Güven Skoruna Göre</option><option>Şikayet yoğunluğuna göre</option></select></div><div class="pills">${['Tüm Markalar','Güvenilir Markalar','Sertifikalı Markalar','Kara Liste','Yeni Markalar','Yüksek Risk'].map(x=>btn(x,x+' filtresi açıldı','pill')).join('')}</div><div class="brand-list">${brands.map(brandCard).join('')}</div></section>`}
function league(){return `<section class="panel">${title('Türkiye Marka Güvenliği Ligi','Güvenlik, kullanıcı memnuniyeti ve hizmet kalitesine göre markalar arası rekabet.')}<div class="tabs">${['Liderlik Tablosu','Aktif Yarışmalar','Performans Metrikleri','Kara Liste'].map((x,i)=>`<button class="${i?'':'active'}" data-action="${x} açıldı">${x}</button>`).join('')}</div><div class="league">${brands.map((b,i)=>`<article><b>#${i+1}</b><div><h3>${b.name}</h3><p>${b.tag} · ${b.labels.slice(0,2).join(' / ')}</p></div><strong>${b.score}</strong><span>${i===0?'+12 sıra':i===1?'+4 sıra':'-9 sıra'}</span></article>`).join('')}</div></section>`}
function contributors(){return `<section class="panel">${title('En Aktif Katkı Sağlayanlar','Topluluk için en çok katkı sağlayan, güvenilir ve deneyimli üyelerimiz.')}<div class="cards4">${users.map(u=>`<article class="glass"><div class="avatar">${u[0][0]}</div><h3>${u[0]}</h3><p>${u[1]}</p><div class="bar"><span style="width:${Math.min(u[2]*2,100)}%"></span></div><b>Level ${u[2]} · ${u[3]}</b>${tags(u[4].split(','))}<div class="mini"><span>${u[5]} İnceleme</span><span>${u[6]} Çözüm</span></div></article>`).join('')}</div></section>`}
function trust(){return `<section class="panel">${title('Güvenlik ve Şeffaflık','Platform güvenliğimiz, kullanıcı doğrulama sistemimiz ve şeffaflık politikalarımız.')}<div class="metrics">${metric('98.5%','Platform Güvenlik Skoru')}${metric('96.8%','Topluluk Güven Oranı')}${metric('94.2%','Şeffaflık Puanı')}${metric('97.1%','Yanıt Hızı Skoru')}</div><div class="status"><span>99.9% Uptime</span><span>2.3s Ortalama Yanıt</span><span>0 Güvenlik İhlali</span><span>Tüm Sistemler Çalışıyor</span></div></section>`}
function home(){return `<section class="hero"><small>Türkiye’nin #1 Şikayet ve Marka Güvenliği Platformu</small><h1>Güvenli Karar<br><span>Kontrol Sende</span></h1><p>Yapay zekâ destekli risk analizi ile markaları değerlendir, toplulukla deneyim paylaş ve güvenli karar sürecini yönet.</p><div class="actions">${a('/marka-ligi','Marka Skorlarını İncele','primary-btn')}${a('/sikayetler','Şikayet Oluştur','secondary-btn')}</div></section><div class="metrics">${metric('150+','Güvenilir Marka')}${metric('50K+','Aktif Kullanıcı')}${metric('12K+','Çözülen Şikayet')}${metric('%98','Güven Skoru')}</div>${brandSection()}${league()}${contributors()}${trust()}`}
function generic(h,p,tabs,body){return `<section class="page-head"><h1>${h}</h1><p>${p}</p></section><section class="panel"><div class="tabs">${tabs.map((x,i)=>`<button class="${i?'':'active'}" data-action="${x} açıldı">${x}</button>`).join('')}</div>${body}</section>`}
function responsible(){let w=['Borç alarak işlem yapmak','Kayıpları geri kazanmak için daha fazla risk almak','Yakın çevreye gerçek durumu saklamak','Süre kontrolünü kaybetmek','Sosyal ilişkileri ihmal etmek','Ara verince huzursuzluk hissetmek'];return generic('Güvenli ve Sorumlu Kullanım','Deneyiminizi kontrol altında tutun, sağlıklı sınırlar belirleyin ve gerektiğinde yardım alın.',['Genel Bakış','Kendini Değerlendir','Kontrol Araçları','Yardım Al'],`<div class="cards4">${['Zaman Kontrolü','Bütçe Yönetimi','Duygusal Kontrol','Sosyal Destek'].map(x=>`<article class="glass"><h3>${x}</h3><p>Limit, takip ve erken uyarı araçları.</p>${btn('Aracı Aç',x+' aracı açıldı')}</article>`).join('')}</div><div class="warn wide"><b>Uyarı İşaretleri</b>${w.map(x=>`<p>${x}</p>`).join('')}</div>`)}
function psychology(){return generic('Psikolojik Farkındalık Testi','Kullanım alışkanlıklarınızın psikolojik boyutlarını değerlendirin ve sağlıklı davranışlar geliştirin.',['Psikolojik Tuzaklar','Psikolojik Test','Duygusal Durumlar','Kontrol Araçları','Eğitim Kaynakları'],`<div class="metrics">${metric('15','Soru')}${metric('5-8 dk','Süre')}${metric('%100','Anonim')}${metric('Anında','Sonuç')}</div><article class="test"><span>Soru 1/15</span><h3>Günde ortalama ne kadar süre platform ve risk değerlendirme aktiviteleriyle geçirirsiniz?</h3>${['30 dakikadan az','30 dakika - 2 saat','2-5 saat','5 saatten fazla'].map(x=>`<label><input type="radio" name="t"/> ${x}</label>`).join('')}<div class="actions">${btn('Teste Başla','Psikolojik test başlatıldı','primary')}${btn('Uzman Desteği Al','Uzman destek paneli açıldı')}</div></article>`)}
function wellness(){return generic('Ruh Sağlığı ve Wellness Merkezi','Sağlıklı alışkanlıklar geliştirin, uzman desteği alın ve toplulukla birlikte iyileşin.',['Wellness Programları','Destek Hizmetleri','Kaynaklar','Topluluk'],`<div class="metrics">${metric('1,247','Aktif Katılımcı')}${metric('89','Tamamlanan Program')}${metric('4.8/5','Memnuniyet')}${metric('24','Uzman Danışman')}</div><div class="cards4">${['Mindful Program','Healthy Limits Workshop','7/24 Kriz Hattı','Online Terapi Seansları'].map(x=>`<article class="glass"><h3>${x}</h3><p>Güvenli destek ve yönlendirme.</p>${btn('Programa Katıl',x+' kaydı açıldı','primary')}</article>`).join('')}</div><div class="emergency"><h3>Acil Durum Desteği</h3><p>Kendinize zarar verme düşünceleriniz varsa hemen yardım alın.</p><b>0850 123 45 67</b>${btn('Canlı Destek','Canlı destek başlatıldı')}</div>`)}
function community(){return generic('Birlikte İyileşiyoruz','Güvenli bir ortamda deneyimlerinizi paylaşın, destek alın ve başkalarına ilham verin.',['Forum','Etkinlikler','Başarı Hikayeleri','Mentorluk'],`<div class="metrics">${metric('50,247','Toplam Üye')}${metric('1,247','Aktif Tartışma')}${metric('8,934','Deneyim')}${metric('15,678','Destek')}</div><div class="cards4">${['Destek ve Yardım','İyileşme Hikayeleri','İpuçları ve Stratejiler','Genel Sohbet'].map(x=>`<article class="glass"><h3>${x}</h3><p>Topluluk kategorisi.</p>${btn('Kategoriye Git',x+' kategorisi açıldı')}</article>`).join('')}</div>`)}
function ai(){return `<section class="page-head"><h1>Yapay Zeka Destekli Rehberlik</h1><p>Kişiselleştirilmiş AI danışmanlarımızdan güvenlik, psikoloji ve strateji konularında destek alın.</p></section><section class="ai"><aside>${['Dr. Psikoloji','Güvenlik Uzmanı','Analiz Uzmanı','Kişisel Danışman'].map((x,i)=>`<button class="${i?'':'active'}" data-action="${x} seçildi">${x}<span>%${95+i} güven</span></button>`).join('')}</aside><article><div class="msg ai-msg">Merhaba. Marka güvenliği, psikolojik kontrol ve şikayet analizi için buradayım.</div><div class="msg user-msg">Bu marka güvenilir mi?</div><div class="msg ai-msg">Lisans, ödeme performansı, şikayet yoğunluğu ve topluluk sinyallerine göre analiz edebilirim.</div><div class="chat"><input placeholder="Mesajınızı yazın...">${btn('Gönder','AI mesaj demo yanıtı üretildi','primary')}</div></article><aside>${['Bu marka güvenilir mi?','Sağlıklı limitler nedir?','Kayıp kovalama nasıl önlenir?','Bonus şartları nasıl değerlendirilir?','Duygusal kontrol teknikleri neler?'].map(x=>btn(x,x+' sorusu seçildi')).join('')}</aside></section>`}
function programs(){return generic('Farkındalık Programları','Katılın, öğrenin ve topluluk katkı puanları kazanın.',['Aktif Programlar','Geçmiş Programlar','Kurallar','Liderlik'],`<article class="campaign"><h3>Yılbaşı Farkındalık Programı</h3><p>Güvenli karar, limit yönetimi ve şeffaflık odaklı topluluk programı.</p><div class="prizes"><span>₺50,000 katkı havuzu</span><span>Eğitim Paketi</span><span>Uzman Görüşmesi</span><span>100 rozet</span></div><p>Katılım Durumu: 2,847 / 5,000</p>${btn('Programa Katıl','Program katılım modalı açıldı','primary')}</article>`)}
function marketplace(){let s=['İtibar ve Şeffaflık Yönetimi','Kullanıcı Bilgilendirme Sistemi','Bildirim ve Bilgilendirme Paketi','Topluluk Kanal Yönetimi','Topluluk İletişimi','SEO ve Şeffaflık İçeriği'];return generic('Şeffaflık Çözümleri Merkezi','Markanız için ihtiyaç duyduğunuz şeffaflık ve kullanıcı iletişimi hizmetlerini tek yerden alın.',['Hizmetler','Sağlayıcılar','Siparişlerim','Satıcı Ol'],`<div class="cards3">${s.map(x=>`<article class="glass"><small>Doğrulanmış</small><h3>${x}</h3><p>Sağlayıcı: Güveniyorum Partner · Puan: 4.8 · Teslim: 3-7 gün</p>${btn('Sipariş Ver',x+' sipariş modalı açıldı','primary')}</article>`).join('')}</div>`)}
function certificate(){return generic('Güvenilirliğinizi Belgeleyin','Guveniyorum.com güven sertifikası ile kullanıcılara güvenilirliğinizi kanıtlayın.',['Sertifika Seviyeleri','Başvuru Yap','Sertifikalı Markalar','Süreç'],`<div class="cards3">${['Temel Güven Sertifikası — ₺2,500/yıl','Gelişmiş Güven Sertifikası — ₺7,500/yıl','Premium Güven Sertifikası — ₺15,000/yıl'].map(x=>`<article class="glass"><h3>${x}</h3><p>SSL, lisans, müşteri hizmetleri, ödeme güvenliği, KYC, denetim ve monitoring gereksinimleri.</p>${btn('Başvuru Yap',x+' başvuru formu açıldı','primary')}</article>`).join('')}</div>`)}
function brandManage(){return generic('Marka İtibarınızı Yönetin','Markanızın güvenilirliğini artırın, müşteri geri bildirimlerini yönetin ve itibarınızı koruyun.',['Dashboard','İncelemeler','Şikayetler','Analitik','Ayarlar'],`<div class="brand-manage"><article class="glass"><h3>Kullanıcı İncelemesi</h3><p>5 yıldız · Şeffaf ve hızlı süreç.</p>${btn('Yanıtla','Yanıtla modalı açıldı')}${btn('Rapor Et','Rapor edildi')}</article><form class="form"><label>Marka Adı<input value="GüvenMark"></label><label>Marka Açıklaması<textarea>Güvenlik odaklı marka profili.</textarea></label><label>İletişim E-postası<input value="iletisim@guvenmark.example"></label><label>Telefon<input value="+90 850 000 00 00"></label><div class="actions">${btn('İptal','Değişiklik iptal edildi')}${btn('Değişiklikleri Kaydet','Marka ayarları kaydedildi','primary')}</div></form></div>`)}
function complaints(){let ok=created?`<article class="success"><h3>Şikayet dosyan oluşturuldu.</h3><p>Dosya No: <b>GVN-2026-0001</b></p><p>Durum: <b>Moderasyon incelemesinde</b></p></article>`:'';return `<section class="page-head"><h1>Şikayetler</h1><p>Kullanıcı deneyimini kayda al, kanıt ekle, marka yanıtını ve çözüm durumunu tek dosya üzerinden takip et.</p></section><section class="panel"><div class="pills">${btn('Şikayet Oluştur','Şikayet formuna geçildi','primary')}${['Tümü','Yeni','Moderasyon İncelemesinde','Marka Yanıtı Bekleniyor','Çözüm Sürecinde','Çözüldü','Doğrulanamadı','Reddedildi','Riskli'].map(x=>btn(x,x+' filtresi açıldı','pill')).join('')}</div>${ok}<div class="complaints"><form id="complaint-form" class="form">${['Marka adı','Domain','Şikayet başlığı','Olay tarihi','İşlem tutarı','Ödeme yöntemi','Talep edilen çözüm'].map(x=>`<label>${x}<input required placeholder="${x}"></label>`).join('')}<label>Şikayet konusu<select><option>Para çekim sorunu</option><option>Ödeme gecikmesi</option><option>Hesap kapatma / kısıtlama</option><option>Şart ve çevrim sorunu</option><option>Müşteri desteği sorunu</option><option>Lisans / şeffaflık sorunu</option><option>Kimlik doğrulama problemi</option><option>Haksız bakiye silme</option><option>Diğer</option></select></label><label>Açıklama<textarea required placeholder="Olayı açık ve kronolojik şekilde anlatın."></textarea></label><label>Kanıt yükle<input type="file"></label><label>Gizlilik tercihi<select><option>Adım gizli kalsın</option><option>Profilim görünsün</option></select></label><label class="check"><input type="checkbox" checked> Yayın ve moderasyon onayını kabul ediyorum.</label>${btn('Şikayet Dosyası Oluştur','', 'primary')}</form><div class="feed">${[['GVN-2026-0001','GüvenMark','Para çekim gecikmesi','Moderasyon İncelemesinde'],['GVN-2026-0002','RiskMark','Şart itirazı','Marka Yanıtı Bekleniyor'],['GVN-2026-0003','SafeMark','Kimlik doğrulama süreci','Çözüldü']].map(x=>`<article class="complaint"><span>${x[0]}</span><h3>${x[1]} — ${x[2]}</h3><p>${x[3]} · Kanıt seviyesi takipte</p>${btn('Dosyayı Gör',x[0]+' detay paneli açıldı')}</article>`).join('')}</div></div></section>`}
const pages={'/':home,'/marka-ligi':()=>`<section class="page-head"><h1>Türkiye Marka Güvenliği Ligi</h1><p>Güvenlik, kullanıcı memnuniyeti ve hizmet kalitesine göre markalar arası rekabet.</p></section>${league()}${brandSection()}`,'/kullanici-yarismasi':()=>`<section class="page-head"><h1>En Aktif Katkı Sağlayanlar</h1><p>Topluluk için en çok katkı sağlayan üyelerimiz.</p></section>${contributors()}`,'/guven-merkezi':trust,'/sorumlu-kullanim':responsible,'/kullanici-psikolojisi':psychology,'/wellness-merkezi':wellness,'/topluluk-merkezi':community,'/ai-danisman':ai,'/sertifikasyon':()=>generic('Sertifikasyon','Lisans doğrulaması, operasyon geçmişi, ödeme disiplini ve şikayet çözüm performansı üzerinden değerlendirilir.',['Genel Bakış','Denetim','Raporlar'],trust()),'/farkindalik-programlari':programs,'/sohbet':()=>generic('Sohbet','Topluluk üyeleri ve marka temsilcileri için moderasyonlu canlı sohbet alanı.',['Genel','Destek','Markalar'],'<div class="glass"><h3>Canlı sohbet demo akışı</h3><p>247 aktif konuşma.</p></div>'),'/sikayetler':complaints,'/seffaflik-marketplace':marketplace,'/sertifika-basvurusu':certificate,'/marka-yonetimi':brandManage,'/yardim':()=>generic('Yardım','Platform kullanımı, güvenlik, şikayet süreci ve marka doğrulama hakkında destek merkezi.',['SSS','İletişim','Rehberler'],'<div class="glass"><h3>Yardım merkezi</h3><p>En sık sorulan sorular ve süreç anlatımları.</p></div>'),'/giris-yap':()=>`<section class="auth"><h1>Giriş Yap</h1><p>Şikayet geçmişine, marka takip listene ve güven skorlarına eriş.</p><form class="form"><label>E-posta<input type="email"></label><label>Şifre<input type="password"></label>${btn('Giriş Yap','Giriş demo durumu açıldı','primary')}</form></section>`,'/uye-ol':()=>`<section class="auth"><h1>Üye Ol</h1><p>Şikayet oluştur, markaları takip et ve topluluk katkı sistemine dahil ol.</p><form class="form"><label>E-posta<input type="email"></label><label>Şifre<input type="password"></label>${btn('Hesap Oluştur','Üyelik demo durumu açıldı','primary')}</form></section>`};
function sidebar(path){return `<aside class="sidebar ${mobile?'open':''}"><div class="logo"><b>G</b><div><strong>Güveniyorum</strong><span>Kontrol Sende</span></div></div><nav>${menu.map(([p,l,b])=>`<a href="${p}" data-route class="${path===p?'active':''}"><span>${l}</span>${b?`<em>${b}</em>`:''}</a>`).join('')}</nav><div class="stats"><p><span>Online Kullanıcı</span><b>1,247</b></p><p><span>Aktif Yarışma</span><b>3</b></p><p><span>Günlük Katkı</span><b>₺2,500</b></p><p><span>Güven Skoru</span><b>%98.5</b></p></div></aside>`}
function topbar(){return `<header class="topbar"><button data-menu>☰</button><input placeholder="Marka ara, şikayet bul, kullanıcı ara..."><div><button data-action="Bildirim paneli açıldı">🔔</button><button data-action="Mesaj paneli açıldı">💬</button><button data-action="Ayarlar açıldı">⚙️</button>${a('/giris-yap','Giriş Yap','ghost-btn')}${a('/uye-ol','Üye Ol','primary-btn small')}</div></header>`}
function modalBox(){return modal?`<div class="modal"><article><button data-close>×</button><h3>İşlem Hazır</h3><p>${modal}</p><small>Bu demo state boş CTA kalmaması için eklendi; gerçek entegrasyonda ilgili API akışına bağlanır.</small></article></div>`:''}
function render(){let p=norm(location.pathname),page=pages[p]||pages['/'];q('#root').innerHTML=`${sidebar(p)}<main>${topbar()}<div class="wrap">${page()}</div></main><button class="live" data-action="Canlı destek başlatıldı">Canlı Destek</button>${modalBox()}`;document.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();nav(x.getAttribute('href'))});document.querySelectorAll('[data-action]').forEach(x=>x.onclick=()=>{let m=x.getAttribute('data-action');if(m){modal=m;render()}});let c=q('[data-close]');if(c)c.onclick=()=>{modal='';render()};let me=q('[data-menu]');if(me)me.onclick=()=>{mobile=!mobile;render()};let f=q('#complaint-form');if(f)f.onsubmit=e=>{e.preventDefault();created=true;modal='Şikayet dosyan oluşturuldu. Dosya No: GVN-2026-0001 · Durum: Moderasyon incelemesinde';render()}}
addEventListener('popstate',render);render();